--INI MEMBUAT DATABASE UNTUK LOGIN
CREATE DATABASE PerpusCRUD
USE PerpusCRUD

--INI MEMBUAT TABEL LOGIN
CREATE TABLE BIO(
USERNAME VARCHAR(5) PRIMARY KEY,
NAMA_ADMIN VARCHAR (50) NOT NULL,
PASS VARCHAR (20) NOT NULL,
);

--INI MEMASUKAN DATA KE TABEL BIO UNTUK LOGIN
INSERT INTO BIO VALUES ('admin','admin99','admin')

--INI MENAMPILKAN DATA BIO
SELECT * FROM BIO